import RPi.GPIO as G
G.setmode(G.BOARD)
G.setwarnings(False)
G.setup(3, G.OUT)
G.setup(5, G.OUT)
G.setup(7, G.OUT)
G.setup(8, G.OUT)
G.setup(10, G.OUT)
G.setup(11, G.OUT)
G.setup(12, G.OUT)
G.setup(13, G.OUT)
G.setup(15, G.OUT)
G.setup(16, G.OUT)
G.setup(18, G.OUT)
G.setup(19, G.OUT)
G.setup(21, G.OUT)
G.setup(22, G.OUT)
G.setup(23, G.OUT)
G.setup(24, G.OUT)
G.setup(26, G.OUT)
G.setup(29, G.OUT)
G.setup(31, G.OUT)
G.setup(32, G.OUT)
G.setup(33, G.OUT)
G.setup(35, G.OUT)
G.setup(36, G.OUT)
G.setup(37, G.OUT)
G.setup(38, G.OUT)
G.setup(40, G.OUT)
